x-db-env: &db_env
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres

x-rails-env: &rails_env
  DB_HOST: db_mirroring
  HOST: "0.0.0.0"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  BUNDLE_PATH: /bundle
  REDIS_URL: redis://redis_mirroring:6379/1

services:
  app_mirroring:
    container_name: app_mirroring
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./.bashrc:/root/.bashrc:ro,cached
      - ..:/workspace:cached
      - bundle_cache_mirroring:/bundle
    ports:
      - "3001:3000"
    command: sleep infinity
    environment:
      <<: *rails_env
    depends_on:
      - db_mirroring
      - redis_mirroring

  worker_mirroring:
    container_name: worker_mirroring
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bundle_cache_mirroring:/bundle
    command: bundle exec sidekiq
    restart: unless-stopped
    environment:
      <<: *rails_env
    depends_on:
      - redis_mirroring

  redis_mirroring:
    container_name: redis_mirroring
    image: redis:latest
    volumes:
      - redis-data-mirroring:/data
    restart: unless-stopped

  db_mirroring:
    container_name: db_mirroring
    image: postgres:16
    volumes:
      - postgres-data-mirroring:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      <<: *db_env

volumes:
  postgres-data-mirroring:
  redis-data-mirroring:
  bundle_cache_mirroring:


